
name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

env:
  IMAGE: test
 
jobs:
  build:
    
    if: github.ref == 'refs/heads/master'
    env:
      GKE_PROJECT: ${{ secrets.MASTER_GKE_PROJECT }}
      GKE_CLUSTER: ${{ secrets.MASTER_GKE_CLUSTER }}
      GKE_REGION: ${{ secrets.MASTER_GKE_REGION }}
      GKE_SA: ${{ secrets.MASTER_SA_EMAIL }}
      GKE_ACC_KEY: ${{ secrets.MASTER_GOOGLE_APPLICATION_CREDENTIALS }}
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2    

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: $GKE_SA
        service_account_key: $GKE_ACC_KEY
    
    - run: |
        gcloud auth configure-docker    
        
    - name: Docker Build
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD}}
        docker build -t vincentngai86/github_action:$GKE_PROJECT-$IMAGE-GITHUB_SHA \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .
        docker push vincentngai86/github_action:$GKE_PROJECT-$IMAGE-$GITHUB_SHA
      
    - name: modify image tag
      run: |
        sed  -i -e "s/^  image: .*/  image: vincentngai86/github_action:$GKE_PROJECT-$IMAGE-$GITHUB_SHA/g" deployment.yaml
        cat deployment.yaml | grep image
