name: Build and Deploy to GKE

on:
  push:
    branches:
    - develop
    - master

env:
  IMAGE: test
  DEPLOY_NAMESPACE: vincent

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Export ENV for Prod
      if: contains(github.ref, 'refs/heads/master')
      run: |
          echo "::set-env name=GKE_PROJECT::${{ secrets.MASTER_GKE_PROJECT }}"
          echo "::set-env name=GKE_CLUSTER::${{ secrets.MASTER_GKE_CLUSTER }}"
          echo "::set-env name=GKE_REGION::${{ secrets.MASTER_GKE_REGION }}"

    - name: Export ENV for DEV
      if: contains(github.ref, 'refs/heads/develop')
      run: |
          echo "::set-env name=GKE_PROJECT::${{ secrets.DEV_GKE_PROJECT }}"
          echo "::set-env name=GKE_CLUSTER::${{ secrets.DEV_GKE_CLUSTER }}"
          echo "::set-env name=GKE_REGION::${{ secrets.DEV_GKE_REGION }}"
                 
    - name: Switch Cluster if Branch is Master
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      if: github.ref == 'refs/heads/master'
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.MASTER_SA_EMAIL }} 
        service_account_key: ${{ secrets.MASTER_GOOGLE_APPLICATION_CREDENTIALS }} 
        export_default_credentials: true

    - name: Switch Cluster if Branch is develop
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      if: github.ref == 'refs/heads/develop'
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.MASTER_SA_EMAIL }} 
        service_account_key: ${{ secrets.MASTER_GOOGLE_APPLICATION_CREDENTIALS }} 
        export_default_credentials: true

    - name: Get Auth to GKE
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $GKE_PROJECT   
        
    - name: Deploy Helm
      run: |
        kubectl apply -f deployment.yaml -n $DEPLOY_NAMESPACE
        curl -o helm.gz https://get.helm.sh/helm-v2.13.1-linux-amd64.tar.gz
        tar -zxvf helm.gz
        cp linux-amd64/helm /usr/local/bin
        helm version
