
name: Build and Deploy to GKE

on:
  push:
    branches:
    - develop
    - master

env:
  IMAGE: test

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: sed
      run: sed -ie "s/\s\simage:.*/\s\simage:\svincentngai86\/github_action:$GKE_PROJECT-$IMAGE-$GITHUB_SHA/g" deployment.yaml

    
