name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Export ENV for Prod
      if: contains(github.ref, 'refs/heads/master')
      run: |
          echo "::set-env name=MASTER_VAULT_SERVER::${{ secrets.MASTER_VAULT_SERVER }}"
          echo "::set-env name=MASTER_VAULT_PATH::${{ secrets.MASTER_VAULT_PATH }}"
          echo "::set-env name=MASTER_VAUTL_TOKEN::${{ secrets.MASTER_VAUTL_TOKEN }}"

    - name: Export ENV Var from vault
      run: |
        for s in $(curl -s --header "X-Vault-Token: afa27e11-5b83-c40a-b74b-78c5b7bdffad" https://vault.gogo.tech:8200/v1/gogotech/gogovan-server/qa/github_action_deploy | jq -r ".data|to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]"); do
          export $s
        done
    - name: Print Env var
      run: |
          echo 1 - $TEST1
          echo 2 - $TEST2
