
name: Build and Deploy to GKE

on:
  push:
    branches:
    - develop
    - master

env:
  IMAGE: test

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Export ENV Prod
      if: contains(github.ref, 'refs/heads/master')
      run: |
          echo "::set-env name=GKE_PROJECT::${{ secrets.MASTER_GKE_PROJECT }}"
          echo "::set-env name=GKE_CLUSTER::${{ secrets.MASTER_GKE_CLUSTER }}"
          echo "::set-env name=GKE_REGION::${{ secrets.MASTER_GKE_REGION }}"

    - name: Export ENV DEV
      if: contains(github.ref, 'refs/heads/develop')
      run: |
          echo "::set-env name=GKE_PROJECT::${{ secrets.DEV_GKE_PROJECT }}"
          echo "::set-env name=GKE_CLUSTER::${{ secrets.DEV_GKE_CLUSTER }}"
          echo "::set-env name=GKE_REGION::${{ secrets.DEV_GKE_REGION }}"
        
          
    - name: Switch Cluster if Prod
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      if: github.ref == 'refs/heads/master'
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.MASTER_SA_EMAIL }} 
        service_account_key: ${{ secrets.MASTER_GOOGLE_APPLICATION_CREDENTIALS }} 
        export_default_credentials: true

    - name: Switch Cluster if Dev
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      if: github.ref == 'refs/heads/develop'
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.DEV_SA_EMAIL }} 
        service_account_key: ${{ secrets.DEV_GOOGLE_APPLICATION_CREDENTIALS }} 
        export_default_credentials: true
  
    - name: Get GKE
      run: |
        gcloud auth configure-docker 
        gcloud info
        gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $GKE_PROJECT   
        
    - name: Get Cluster 
      run: |
        kubectl get ns


    
    
