
name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

env:
  IMAGE: test
 
jobs:
  build:
    
    if: github.ref == 'refs/heads/master'
    env:
      GKE_PROJECT: ${{ secrets.MASTER_GKE_PROJECT }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    

    - name: Run a multi-line script
      run: |
        echo $GKE_PROJECT

    # Configure docker login
    - run: |
        docker login -u vincentngai86 -p ${{ secrets.DOCKER_HUB_PASSWORD}}

    # Build the Docker image
    - name: Build
      run: |
        docker build -t vincentngai86/github_action/$GKE_PROJECT-$IMAGE:$GITHUB_SHA \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .
           
    - name: Publish
      run: |
        docker push vincentngai86/github_action/$GKE_PROJECT-$IMAGE:$GITHUB_SHA
#jobs:
#  setup-build-publish-deploy:
#    name: Setup, Build, Publish, and Deploy
#    runs-on: ubuntu-latest
#    steps:
#
#    - name: Checkout
#      uses: actions/checkout@master
#
#    # Setup gcloud CLI
#    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#      with:
#        version: '270.0.0'
#        service_account_email: ${{ secrets.SA_EMAIL }}
#        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#
#    # Configure docker to use the gcloud command-line tool as a credential helper
#    - run: |
#        gcloud auth configure-docker
#
#    # Configure docker login
#    - run: |
#        docker login -u ${secrets.DOCKER_HUB_USER} -p ${secrets.DOCKER_HUB_PASSWORD}
#
#    # Build the Docker image
#    - name: Build
#      run: |
#        docker build -t gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA \
#          --build-arg GITHUB_SHA="$GITHUB_SHA" \
#          --build-arg GITHUB_REF="$GITHUB_REF" .
#
#    # Push the Docker image to Google Container Registry
#    - name: Publish
#      run: |
#        docker push gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA
