name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Export ENV for Prod
      if: contains(github.ref, 'refs/heads/master')
      run: |
          echo "::set-env name=VAULT_SERVER::${{ secrets.MASTER_VAULT_SERVER }}"
          echo "::set-env name=VAULT_PATH::${{ secrets.MASTER_VAULT_PATH }}"
          echo "::set-env name=VAUTL_TOKEN::${{ secrets.MASTER_VAUTL_TOKEN }}"
          echo "::set-env name=MYENV::master
    
    - name: Export from vault-action
      uses: RichiCoder1/vault-action
      with:
        url: https://$VAULT_SERVER
        token: $VAUTL_TOKEN
        secrets: |
            $VAULT_PATH TEST1 | T001 ;
            $VAULT_PATH TEST2 | T002 ;
