name: Build and Deploy to GKE

on:
  push:
    branches:
    - develop
    - master
env:
  COUNTRY: HK SG TW

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Export ENV Var from vault
      run: |
        for c in $COUNTRY do
          echo $c
        done
