name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Export ENV for Prod
      if: contains(github.ref, 'refs/heads/master')
      run: |
          echo "::set-env name=MASTER_VAULT_SERVER::${{ secrets.MASTER_VAULT_SERVER }}"
          echo "::set-env name=MASTER_VAULT_PATH::${{ secrets.MASTER_VAULT_PATH }}"
          echo "::set-env name=MASTER_VAUTL_TOKEN::${{ secrets.MASTER_VAUTL_TOKEN }}"

    - name: Export ENV Var from vault
      run: |
        printenv
        TEMP=$(curl -s --header "X-Vault-Token: $MASTER_VAUTL_TOKEN" --request GET  https://$MASTER_VAULT_SERVER/$MASTER_VAULT_PATH |jq -r  '.data| to_entries[] |.key+"="+.value')
        for key in $TEMP;
        do
         K=$(echo $key|cut -d ':' -f 1)
         V=$(echo $key|cut -d ':' -f 2-)
         export $K=$V
        done
        printenv
